### ISSUE TITLE
Disallow `in` operators.

### ISSUE THREAD

**Issue by mysticatea** [mysticatea/eslint-plugin#10]
http://stackoverflow.com/questions/13866442/why-is-javascripts-in-operator-consistently-slower-than-strict-member-compari

**Comment by graingert** [comment]
in can be optimized away:

> Apparently engines are not yet smart enough to optimize away "bar" in foo, but it's only a matter of time. And priorities.

Although it might be a correctness issue? Maybe people should be using Map, instead?

**Comment by mysticatea** [comment]
I was surprised that the performance between `obj.foo !== undefined` and `"foo" in obj` is huge different even if `foo` is constant. E.g., this will be used for the type check of overloading.

On the other hand, in the cases that `Map` fits, `foo` is dynamic, the performance between `obj[foo] !== undefined` and `foo in obj` is not different. Yes, in this case, `Map` is good choice.

**Comment by graingert** [comment]
It makes me wonder about the performance of `obj.foo !== undefined || "foo" in obj` for cases where `{foo: undefined}`

**Comment by mysticatea** [comment]
Closing as I can disallow `in` operators with `no-restricted-syntax` rule.
