### ISSUE TITLE
extend no-useless-rest-spread to properties

### ISSUE THREAD

**Issue by graingert** [mysticatea/eslint-plugin#11]
**Please describe what the rule should do:**
Prevent rest/spread overcomplication 
**What category of rule is this? (place an "X" next to just one item)**

[x] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
// bad
const foo = {
    ...{a, value: x + 3},
    ...stuff,
};

const bar = [
   ...[a, b, c],
   ...otherStuff,
]

foo(...[a, b, c])

function foo(a, b, ...[c, d]) {
}

// good
const foo = {
    a,
    value: x + 3,
    ...stuff,
};

const bar = [
   a,
   b,
   c,
   ...otherStuff,
]

foo(a, b, c)

function foo(a, b, c, d) {
}
```

**Why should this rule be included in ESLint-plugin (instead of a Eslint)?**
I wanted to include this rule in https://github.com/bryanrsmith/eslint-plugin-prefer-object-spread see https://github.com/bryanrsmith/eslint-plugin-prefer-object-spread/issues/45#issuecomment-281185216
however @bryanrsmith thought it would be better as a core rule.

> Good idea. I think it would be good to create a new rule for that rather than extend this one. I'd expect ESLint core to start accepting rules around object rest/spread soon, now that the proposal is pretty far along and is starting to be implemented by vendors, so I suggest opening an issue in the main ESLint repo.

I then tried to [request a core rule](https://github.com/eslint/eslint/issues/8118) however rest spread properties are not in ES yet.

**Comment by mysticatea** [comment]
Thank you for this issue.
OK, I'll implement it.

**Comment by mysticatea** [comment]
Parsers seem buggy around this.

- Both `espree` and `babel-eslint` threw syntax errors on `function foo(a, ...[b, c]) {}`.
- `espree` threw syntax errors on `let {a, ...{b, c}} = obj`.
- `babel-eslint` threw syntax errors on `let [a, ...[b, c]] = list`.

**Comment by mysticatea** [comment]
Please try [v4.2.0](https://github.com/mysticatea/eslint-plugin/releases/tag/v4.2.0).

**Comment by graingert** [comment]
👌👌👌👌
