### ISSUE TITLE
rest/spread no-extra-parens

### ISSUE THREAD

**Issue by graingert** [mysticatea/eslint-plugin#13]
**Please describe what the rule should do:**
Remove extra parens from rest/spread property expressions
**What category of rule is this? (place an "X" next to just one item)**

[x] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
// bad
const foo = {
    ...(stuff),
    ...(moreStuff)
};

const bar = [
   ...([a, b, c]),
   ...(otherStuff),
]

// good
const foo = {
    ...stuff,
    ...moreStuff,
};

const bar = [
   ...[a, b, c],
   ...otherStuff,
];

const baz = {
    ...(a ? b : {}),
    ...stuff,
}
```

**Why should this rule be included in ESLint-plugin (instead of a Eslint)?**
rest spread properties are not in ES yet, so I think it's appropriate to try here first.

**Comment by mysticatea** [comment]
Thank you for this issue.

However, I think we should fix this in core.
I reported: https://github.com/eslint/eslint/issues/8175
