### ISSUE TITLE
new rule, prefer numeric separators 

### ISSUE THREAD

**Issue by graingert** [mysticatea/eslint-plugin#20]
A rule for enforcing https://github.com/tc39/proposal-numeric-separator placement

```js
// bad
const x = 1000000000000;
// bad
const x = 1_000_000_0000_00;
// good
const x = 1_000_000_000_000;

// good
const x = 0b1010_0001_1000_0101;

// bad
const x = const x = 0b1010000110000101;
// bad
const x = 0b101_000_011_000_010_1;

// good
const x = 0xA0_B0_C0;
//bad
const x = 0xA0B0_C0D0;
```

**Comment by graingert** [comment]
with the options being:

```
type mode = int||'consistent'|false|null
class OptionObject {
  o: mode = false;
  x: mode = 2;
  b: mode = 4;
  d: mode = 3;
}
const options: mode | OptionObject = new OptionObject();
```
Where:

* 'consistent' means that each _ separate the same number of values throughout the literal.
* an int means how far from the left before the first _ and 'consistent'
* false means no _s at all allowed
* null means _s allowed anywhere or nowhere

**Comment by graingert** [comment]
also might be neat to upgrade the old fashioned way of doing numeric separators:
```js
// bad
const x = 1 * 1000 * 1000;

// good
const x = 1_000_000;
```

**Comment by mysticatea** [comment]
Thank you for the proposal.

The check for consistent usage of numeric separators sounds a good idea. We should add the rule to ESLint core after the syntax proposal arrived at Stage 4.

But, I'm sorry, I don't want to add rules about syntax what [Espree](https://github.com/eslint/espree) doesn't support into this plugin.
Probably [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel) is proper place for the rule for now.

Thank you.
