### ISSUE TITLE
Why setting prettier indent in eslintrc?

### ISSUE THREAD

**Issue by ncaq** [mysticatea/eslint-plugin#24]
英語が苦手なので日本語で失礼します.

* <https://github.com/mysticatea/eslint-plugin/blob/a59386ba1264b6cf25b3a605d651ea43bd096bfe/lib/configs/_ts.js#L61>
* <https://github.com/mysticatea/eslint-plugin/blob/39b0da3375bb10c1459d6527db8193394d6b80de/lib/configs/es2017.js#L17>
* <https://github.com/mysticatea/eslint-plugin/blob/7b792d760f468e9e2e13f88a5554390c121e6879/lib/configs/es5.js#L392>

の3箇所でprettierの細かい設定をされていますが,
これだと困ってしまいます.

まずプロジェクトごとにprettierの設定が異なることがあるので,
eslintrcでインデントルールをベタ書きしてあってしかも`usePrettierrc: false`されていると設定を変更することが出来ません.
とりあえず

~~~json
"@mysticatea/prettier": "off"
~~~

してやり過ごそうとしたのですが,
TypeScript向けに`overrides`されていると単純にrulesで書き換えようとしてもオフにならなくてマージしてこれだけ無効化しようとするのは少々困難です.

もう一つ問題があります.
eslintにprettierのルールが書かれているとeslintを経由せずにprettierを使って整形するツールに設定が伝わりません.

そこでeslint側ではprettierの詳しいルールを書かずに有効にするだけにして,
prettierの設定は[`.prettierrc`](https://prettier.io/docs/en/configuration.html)に任せた方が望ましいと思います.
`.prettierrc`はグローバルに設定することも出来ますし.

デフォルトでprettierの細かい設定をするとしても,
せめて`usePrettierrc: false`は外してプロジェクトの設定を参照するのが望ましいと思います.

どう思いますか?

**Comment by mysticatea** [comment]
Thank you for your issue!

> まずプロジェクトごとにprettierの設定が異なることがあるので,
> eslintrcでインデントルールをベタ書きしてあってしかもusePrettierrc: falseされていると設定を変更することが出来ません.

こちら、私は Prettier 自体を利用していませんのでこうなっています。
Lint/Format 共に ESLint で行っており、`@mysticatea/prettier` は実装の詳細です。その実装が ESLint とは無関係なファイルによって変化するのは、私にとって望ましくありません。 

> TypeScript向けにoverridesされていると単純にrulesで書き換えようとしてもオフにならなくてマージしてこれだけ無効化しようとするのは少々困難です.

ESLint 6 を使うとこのバグは直っていますのでお試しください。

**Comment by ncaq** [comment]
> こちら、私は Prettier 自体を利用していませんのでこうなっています。

それではprettierに関する記述を一切しないか,
するとしても`"off"`にするなどして詳細設定をしないというのが望ましいのではないかと思います.
prettierに操作してほしくないのにprettierの設定をするというのはヘンな気がします.

> ESLint 6 を使うとこのバグは直っていますのでお試しください。

それは嬉しいです. :smile:
しかし現在利用している他のライブラリ達が｢5を超えるな｣と警告してくるので,
6を実運用するのはもう少し先になりそうです.

**Comment by mysticatea** [comment]
> それではprettierに関する記述を一切しないか,
> するとしても"off"にするなどして詳細設定をしないというのが望ましいのではないかと思います.
> prettierに操作してほしくないのにprettierの設定をするというのはヘンな気がします.

ちょっと紛らわしい言い方だったかもです。
私の意図は、「ESLint プラグインの実装の詳細として (ライブラリとして) prettier を利用している」ということです。それは ESLint プラグインの実装の詳細であり、ESLint 以外の設定ファイルによって振る舞いが変わるのは望ましくありません。

**Comment by ncaq** [comment]
なるほど.
全てをeslintrcによって制御したいから`.prettierrc`は書くべきではないという思想でこれを作っているのですね.
私はeslint以外のツールで整形することも想定して`.prettierrc`に書いてそれをeslintが読み込むのが最適だと考えているのですが,それはもう思想の違いですね.
思想の違いでこれは @mysticatea さんの設定なのでバトルをするつもりは無いのですが,
それならばオリジナルルールは将来的に独立させてくれると嬉しいです.
特に @mysticatea/no-this-in-static などは全てのプロジェクトに導入したい(実際にしている)ので,これらを依存関係を膨らませずに設定は別に書いて利用したいので…

**Comment by mysticatea** [comment]
そうですね。

もともとは、mysticatea/eslint-plugin がオリジナルルールをホストし、[mysticatea/eslint-config](https://github.com/mysticatea/eslint-config) が個人設定をホストするようにしていたのですが、 `eslint-config` がプラグインに依存するには `peerDependencies` を使うしかなくて、いちいちインストールするのが手間でした。それで、https://github.com/eslint/eslint/issues/3458#issuecomment-257161846 で提案されたように多数のプラグインを集約するプラグインを作らざるを得なかった、というのが経緯です。

[npm のロードマップ](https://blog.npmjs.org/post/186983646370/npm-cli-roadmap-summer-2019)によると今秋リリース予定の npm 7 で `peerDependencies` の自動インストールが復活するらしいので、そうしたらこのプラグインはオリジナル ルールだけを持つ昔の状態に戻ると思います。
